export const site = {
  name: 'Podalanga',
  title: 'Joshua John L (Podalanga) · Robotics & Control Systems Engineer',
  tagline: 'I build machines that balance, swim and see.',
  description:
    'Joshua John L (Podalanga): robotics and control-systems engineer. EPFL BioRob intern, NIT Trichy ICE, IIT Madras BS Data Science. Projects: ROS 2, LQR, MuJoCo.',
  url: 'https://podalanga.github.io',
  email: 'joshuajohn.nitt@gmail.com',
  socials: {
    github: 'https://github.com/podalanga',
    linkedin: 'https://www.linkedin.com/in/joshuajohnl/',
  },
  /** Who the site is about: feeds the Person JSON-LD, author meta, RSS and llms.txt. */
  person: {
    name: 'Joshua John L',
    givenName: 'Joshua John',
    alternateName: ['Joshua John', 'Podalanga', 'podalanga'],
    jobTitle: 'Robotics & Control Systems Engineer',
    alumniOf: [
      { name: 'National Institute of Technology, Tiruchirappalli', alternateName: 'NIT Trichy', url: 'https://www.nitt.edu' },
      { name: 'Indian Institute of Technology Madras', alternateName: 'IIT Madras', url: 'https://www.iitm.ac.in' },
    ],
    affiliation: { name: 'BioRob, EPFL', url: 'https://www.epfl.ch/labs/biorob/' },
    nationality: 'India',
  },
  /**
   * Topics the person works in. Machine-readable only: fed into Person.knowsAbout (JSON-LD),
   * <meta name="keywords"> and llms.txt. Keep every term truthful; add new ones freely.
   */
  keywords: [
    'Robotics',
    'Control Systems',
    'Control Engineering',
    'Convex Optimization',
    'Optimal Control',
    'Linear Quadratic Regulator (LQR)',
    'Gain Scheduling',
    'Pole Placement',
    'PID Control',
    'State Estimation',
    'Sensor Fusion',
    'IMU / Madgwick Filter',
    'Observer Design',
    'System Modeling',
    'Kinematics and Dynamics',
    'Inverted Pendulum',
    'Mobile Robots',
    'Differential Drive Robots',
    'SLAM',
    'LiDAR',
    'Underwater Robotics',
    'Remotely Operated Vehicles (ROV)',
    'Bio-inspired Robotics',
    'Central Pattern Generators (CPG)',
    'Robotic Arms',
    'Robot Simulation',
    'Physics Simulation',
    'ROS 2',
    'MuJoCo',
    'Gazebo',
    'MATLAB',
    'Simulink',
    'Python',
    'C++',
    'Embedded Systems',
    'Mechatronics',
    'Computer Vision',
    'OpenCV',
    'Machine Learning',
    'Data Science',
    'SolidWorks',
    'Mechanical Design',
    '3D Printing',
    'Instrumentation and Control Engineering',
  ],
  nav: [
    { label: 'PROFILE', index: '00', href: '/' },
    { label: 'PROJECTS', index: '01', href: '/projects/' },
    { label: 'ARCHIVE', index: '02', href: '/archive/' },
    { label: 'BLOG', index: '03', href: '/blog/' },
  ],
  // epoch for the UPTIME telemetry counter: start of work history
  epoch: '2023-08-01T00:00:00+05:30',
  telemetry: {
    coords: [
      { label: 'NIT Trichy', value: '10.7589°N 78.8132°E' },
      { label: 'EPFL', value: '46.5191°N 6.5668°E' },
      { label: 'IIT Madras', value: '12.9915°N 80.2336°E' },
    ],
  },
} as const;
